variables:
  MAVEN_OPTS: "-Xmx2048M -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "- s settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: $ARTIFACTORY_BUILDIMAGE

before_script:
  - echo "$MIRRORS" > /etc/apt/sources.list
  - cat /proc/version
  - apt-get update
  - apt-get install -y maven gawk --no-install-recommends
  - gem install asciidoctor-pdf --pre
  - asciidoctor-pdf -v

stages:
  - package

cache:
  paths:
    - .m2/repository

.template: &vorlage
  stage: package
  tags:
    - docker
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$CI_JOB_ID"
    paths:
    - "target/html"
    - "target/pdf"
  script:
    - 'mvn $MAVEN_CLI_OPTS package'

package:branches:
  <<: *vorlage
  artifacts:
    expire_in: 2 weeks
  only:
    - branches@IsyFact/isy-documentation
  except:
    - master@IsyFact/isy-documentation
    
package:master:
  <<: *vorlage
  only:
    - master@IsyFact/isy-documentation

.build:jdk8:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS compile'
    - 'rsync -av --delete target/html/* rsync://$HTML_DOC_DEPLOY_URL'
